<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>sales.Contracts</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\sales.Data\sales.Data.csproj" />
    </ItemGroup>

</Project>
